### ISSUE TITLE
License

### ISSUE THREAD

**Issue by stfsy** [tasynguyen3894/vue-simple-custom-hooks#1]
Hi @tasynguyen3894  just came across your story on Medium. It's super cool and valuable thanks for sharing it. 

Unfortunately, until there's no license in the repo it is open source, but cannot be used by anyone else besides you. Would it be possible to add a LIcense? MIT or Apache 2 maybe?

**Comment by tasynguyen3894** [comment]
hi @stfsy thank for you isssue. I've updated it.

**Comment by stfsy** [comment]
@tasynguyen3894 thank you!
